### ISSUE TITLE
Illegal character in path in ISpark jar file

### ISSUE THREAD

**Issue by sparkscala** [tribbloid/ISpark#11]
After I used maven twice (first time failed) to create the uber jar file, and setup IScala with spark backend, ipython notebook kernel died. I would like someone to help me find the illegal characters in the source code and fix it. The main error messages are the following:

Exception in thread "main" java.net.URISyntaxException: Illegal character in path at index 60: /home/username/ISpark/core/target/ispark-core-0.2.0-SNAPSHOT.jar}
at java.net.URI$Parser.fail(URI.java:2829)
at java.net.URI$Parser.checkChars(URI.java:3002)
at java.net.URI$Parser.parseHierarchical(URI.java:3086)
at java.net.URI$Parser.parse(URI.java:3044)
at java.net.URI.<init>(URI.java:595)
at org.apache.spark.util.Utils$.resolveURI(Utils.scala:1506)
at org.apache.spark.util.Utils$$anonfun$resolveURIs$1.apply(Utils.scala:1530)
at org.apache.spark.util.Utils$$anonfun$resolveURIs$1.apply(Utils.scala:1530)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
at org.apache.spark.util.Utils$.resolveURIs(Utils.scala:1530)
at org.apache.spark.deploy.SparkSubmitArguments.parse$1(SparkSubmitArguments.scala:307)
at org.apache.spark.deploy.SparkSubmitArguments.parseOpts(SparkSubmitArguments.scala:220)
at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:75)
at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:70)
at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by tribbloid** [comment]
sorry did you accidentally add an extra back bracket "}" in the parameter string? 'cause it looks like that.

Plz post your profile/ parameter string for an easy fix

**Comment by sparkscala** [comment]
Thank you very much for your reply. There was indeed an extra "}". But still the kernel died.
The added part in ipython_config.py is:

import os
c = get_config()

SPARK_HOME = os.environ['SPARK_HOME'] 
# SPARK_HOME is set to /home/wtlu/spark-1.3.0 in ~/.bashrc
MASTER = 'local[2]'

c.KernelManager.kernel_cmd = [SPARK_HOME+"/bin/spark-submit",
 "--master", MASTER,
 "--class", "org.tribbloid.ispark.Main", 
 "--executor-memory", "2G", #ISpark driver takes more memory than most other Spark drivers
 "--jars", "/home/wtlu/ISpark/core/target/ispark-core-0.2.0-SNAPSHOT.jar",
 "/home/wtlu/ISpark/core/target/ispark-core-0.2.0-SNAPSHOT-javadoc.jar",
 "/home/wtlu/IScala-0.1/lib/IScala.jar",
 "--profile", "{connection_file}",
 "--interp", "Spark",
 "--parent"]

The complain is:

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
2015-04-11 20:18:45.772 [NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel fba2d535-06de-48e7-988b-6aaa8381cfe8 restarted
Exception in thread "main" java.lang.NoClassDefFoundError: play/api/libs/json/Reads
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:538)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: play.api.libs.json.Reads
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 7 more

.
.
.

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
2015-04-11 20:18:57.854 [NotebookApp] WARNING | KernelRestarter: restart failed
2015-04-11 20:18:57.855 [NotebookApp] WARNING | Kernel fba2d535-06de-48e7-988b-6aaa8381cfe8 died, removing from map.
ERROR:root:kernel fba2d535-06de-48e7-988b-6aaa8381cfe8 restarted failed!

**Comment by tribbloid** [comment]
looks like a jar hell issue for me, could you remove the redundant:

"/home/wtlu/IScala-0.1/lib/IScala.jar",
"--interp", "Spark",

I assume you don't need IScala as this project is ported from that.
Also pull from me again: I forgot to clean up some imports and update the readme

**Comment by tribbloid** [comment]
and seriously you don't need that java doc jar. It's for human to read, not machines.
That's probably where the jar hell come frome

**Comment by sparkscala** [comment]
I downloaded the new files and remade the jar files. Still kernel died. I did not include the doc jar.
The setting is as you suggested:

import os
c = get_config()

SPARK_HOME = os.environ['SPARK_HOME']
MASTER = 'local[2]'

c.KernelManager.kernel_cmd = [SPARK_HOME+"/bin/spark-submit",
 "--master", MASTER,
 "--class", "org.tribbloid.ispark.Main", 
 "--executor-memory", "2G", #ISpark driver takes more memory than most other Spark drivers
"/home/wtlu/ISpark/core/target/ispark-core-0.2.0-SNAPSHOT.jar",
 "--profile", "{connection_file}",
 "--parent"]

Error message:

wtlu@ubuntu:~$ ipython notebook --profile spark &
[1] 6892
wtlu@ubuntu:~$ 2015-04-12 14:11:16.696 [NotebookApp] Using existing profile dir: u'/home/wtlu/.ipython/profile_spark'
2015-04-12 14:11:16.703 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
2015-04-12 14:11:16.715 [NotebookApp] CRITICAL | WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
2015-04-12 14:11:16.715 [NotebookApp] CRITICAL | WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
2015-04-12 14:11:16.716 [NotebookApp] Serving notebooks from local directory: /home/wtlu
2015-04-12 14:11:16.716 [NotebookApp] 0 active kernels 
2015-04-12 14:11:16.716 [NotebookApp] The IPython Notebook is running at: http://[all ip addresses on your system]:8010/
2015-04-12 14:11:16.716 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

wtlu@ubuntu:~$ INFO:tornado.access:302 GET / (192.168.239.1) 1.04ms
2015-04-12 14:11:32.195 [NotebookApp] Kernel started: c637f5ce-0191-4525-9ac7-1102c2b5684c
Exception in thread "main" java.lang.NoClassDefFoundError: play/api/libs/json/Reads
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:538)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: play.api.libs.json.Reads
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 7 more
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
2015-04-12 14:11:35.198 [NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel c637f5ce-0191-4525-9ac7-1102c2b5684c restarted
Exception in thread "main" java.lang.NoClassDefFoundError: play/api/libs/json/Reads
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:538)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: play.api.libs.json.Reads
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 7 more
.
.
.

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
2015-04-12 14:11:47.295 [NotebookApp] WARNING | KernelRestarter: restart failed
2015-04-12 14:11:47.296 [NotebookApp] WARNING | Kernel c637f5ce-0191-4525-9ac7-1102c2b5684c died, removing from map.
ERROR:root:kernel c637f5ce-0191-4525-9ac7-1102c2b5684c restarted failed!

**Comment by tribbloid** [comment]
Could you also confirm that you are submitting to a Spark 1.3.0 cluster (My environment is Spark standalone cluster on AWS-ubuntu, but this shouldn't matter)?

NoClassDefFound error usually infers a jar hell: several jar has overlapping class definitions in different versions. In your case, it can only be between spark jar and ISpark jar.

**Comment by sparkscala** [comment]
I have spark standalone in a single Ubuntu VM. I switched SPARK_HOME from spark-1.3.0 to 1.2.0, still the same problem. When I use maven to create ISpark jar files, there are some warning of diferent version of scala. I have scala 2.11.5 in Ububtu, not 2.10.4.

wtlu@ubuntu:~$ ls -l ISpark/core/target
total 1324
drwxrwxr-x 2 wtlu wtlu   4096 Apr 12 07:26 analysis
-rw-rw-r-- 1 wtlu wtlu 525759 Apr 12 07:26 ispark-core-0.2.0-SNAPSHOT.jar
-rw-rw-r-- 1 wtlu wtlu 804399 Apr 12 07:27 ispark-core-0.2.0-SNAPSHOT-javadoc.jar
drwxrwxr-x 2 wtlu wtlu   4096 Apr 12 07:26 maven-archiver
drwxrwxr-x 4 wtlu wtlu   4096 Apr 12 07:26 scala
drwxrwxr-x 2 wtlu wtlu   4096 Apr 12 07:26 scala-2.10
drwxrwxr-x 3 wtlu wtlu   4096 Apr 12 07:26 site

**Comment by tribbloid** [comment]
O.M.G that explained so much, My maven file doesn't have a build profile for 2.11.x yet. So maybe its better to have me build the jar for you (or let others to  build it for you), I'll upload the jar tomorrow.

There are significant differences in some "unofficial" Spark-repl API between scala 2.10 & 2.11. And I'm kind of busy working on 3 projects . I need somebody to help porting it to 2.11 or do it myself later.

**Comment by FlytxtRnD** [comment]
I am also facing this issue.
```
Exception in thread "main" java.lang.NoClassDefFoundError: play/api/libs/json/Reads
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:274)
at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:538)
at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: play.api.libs.json.Reads
at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
... 7 more
.
.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
2015-04-12 14:11:47.295 [NotebookApp] WARNING | KernelRestarter: restart failed
2015-04-12 14:11:47.296 [NotebookApp] WARNING | Kernel c637f5ce-0191-4525-9ac7-1102c2b5684c died, removing from map.
ERROR:root:kernel c637f5ce-0191-4525-9ac7-1102c2b5684c restarted failed!
```
My Config file setting is:
```
import os
c = get_config()
c.KernelManager.kernel_cmd = ["/home/meethu/spark-1.3.0/bin/spark-submit",
"--master", "spark://master:7077",
"--class", "org.tribbloid.ispark.Main",\
"--total-executor-cores","5",\
"--executor-memory", "2G", #ISpark driver takes more memory than most other Spark drivers
"/home/meethu/ISpark/core/target/ispark-core-0.2.0-SNAPSHOT.jar",
"--profile", "{connection_file}",
"--parent"]
```

I using Scala 2.10 and my ISpark build is success. Please help.

**Comment by tribbloid** [comment]
all personnel. Please download the 0.2.0-SNAPSHOT pre-release jar for testing.

For least unpredictability please try on scala 2.10.4 and spark 1.3.0  first

**Comment by FlytxtRnD** [comment]
I am using scala 2.10.3 and spark 1.3. Could you please specify where I can download the  0.2.0-SNAPSHOT pre-release jar from? Or is it enough to pull from this repo and build the jar using ./mvn-install.sh?

**Comment by tribbloid** [comment]
Either way should work. The download link is access able through release tab

Yours Peng

**Comment by sparkscala** [comment]
It works, Great!
Thank you very much, Peng!

**Comment by tribbloid** [comment]
Cheers mate, please post me any problems or the issue will be closed in 
3 days.

**Comment by FlytxtRnD** [comment]
It worked..Thank you so much :+1:

**Comment by milos-popovic** [comment]
@tribbloid I was getting this same problem, and resolved it by using the JAR downloaded from releases. Unfortunately, I use IPython 3.0, and the kernel is crashing on code complete. As I can see, there is a branch with the IPython 3.0 code complete bug fix, but when I try compiling it I don't get the large assembly jar, only the smaller core snapshot jar which is missing the play/api/libs/json/Reads.

**Comment by tribbloid** [comment]
the large assembly jar is at core/target/scala-2.10/...assembly...jar
Due to the rolling release the uploaded jar is obsolete, I'll have to do it again at some major release, I may build a pipeline to commit automatically in the future

**Comment by milos-popovic** [comment]
@tribbloid It works now, thanks a lot.
