### ISSUE TITLE
Autocomplete is not working

### ISSUE THREAD

**Issue by tdna** [tribbloid/ISpark#14]
When I press tab key in the notebook the following exception appears in the console:
```java
Exception in thread "RequestsEventLoop" java.lang.RuntimeException: JSON deserialization error: JsResultException(errors:List((/line,List(ValidationError(error.path.missing,WrappedArray()))), (/text,List(ValidationError(error.path.missing,WrappedArray())))))
	at scala.sys.package$.error(package.scala:27)
	at scala.Predef$.error(Predef.scala:142)
	at org.tribbloid.ispark.Communication.recv(Communication.scala:77)
	at org.tribbloid.ispark.Main$EventLoop.run(Main.scala:165)
```

**Comment by tribbloid** [comment]
Roger. Autocompletion has been revised shortly, still testing it for stability and may revert back to old implementation

**Comment by tribbloid** [comment]
To help identify the problem (there are probably more than one - spark-shell is not the most stable component). Could you post the text you have input and the location of the cursor you pressed tab?

**Comment by tribbloid** [comment]
Got your problem: this is unique to IPython 3.x, have to crunch the kernel migration guide to figure out. Thanks a lot for pointing it out!

**Comment by tdna** [comment]
You are welcome! Thank you for your investigation! Possibly you are right.

**Comment by tribbloid** [comment]
Alright people, problem solved. Please checkout from IPython-3.x branch.
This is a backward-incompatible change that will render completion on IPython-2.x malfunctioning.
Please test and report if it fixes your case. As usual, this issue will be closed in 3 days if without objection. No String attached :)

**Comment by tdna** [comment]
I think now it is working perfectly! Thank you!
