### ISSUE TITLE
Shift + Tab operation not works in IPython 3.x

### ISSUE THREAD

**Issue by tdna** [tribbloid/ISpark#15]
When you press shift tab when your console on a variable the following exception triggered and the kernel will freeze:

Exception in thread "RequestsEventLoop" java.lang.RuntimeException: JSON deserialization error: JsResultException(errors:List((/msg_type,List(ValidationError(Enumeration expected of type: class org.tribbloid.ispark.msg.MsgTypes$, but it does not appear to contain the value: inspect_request,WrappedArray())))))
	at scala.sys.package$.error(package.scala:27)
	at scala.Predef$.error(Predef.scala:142)
	at org.tribbloid.ispark.Communication.recv(Communication.scala:77)
	at org.tribbloid.ispark.Main$EventLoop.run(Main.scala:165)

**Comment by tribbloid** [comment]
sorry could you advice me what's the usage of shift-tab? I'm not a Python programmer.

**Comment by tdna** [comment]
It just displays the object's/function's/method's header with the docstring.

**Comment by tribbloid** [comment]
In a pop-up floating frame? That sounds like an advanced feature that is 
not supported by Scala Interpreter (or compiler, as only Scala/Java 
bytecode but not sourcecode will be visible to them). However, I'm 
thinking of using this feature to display other things, like progress 
bar or something else.

**Comment by tdna** [comment]
Yes, a popup. I think handling this exception would be good at least.
Thank you.

**Comment by tribbloid** [comment]
After protocol upgrade the exception no longer exists. But still this is kind of a lackluster. The popup can defintely show something (by hacking into java/scala reflection)
