### ISSUE TITLE
Can't compile against 2.11 & 1.4.0

### ISSUE THREAD

**Issue by elbamos** [tribbloid/ISpark#21]
I get this error:  

info] Compiling 20 Scala sources to /home/aelberg/isparkbuild/ISpark/core/target/scala/classes...
[error] /home/aelberg/isparkbuild/ISpark/core/src/main/scala/org/apache/spark/repl/SparkILoopExt.scala:43: overloaded method constructor SparkILoop with alternatives:
[error]   ()scala.tools.nsc.interpreter.SparkILoop <and>
[error]   (in0: java.io.BufferedReader,out: scala.tools.nsc.interpreter.JPrintWriter)scala.tools.nsc.interpreter.SparkILoop <and>
[error]   (in0: Option[java.io.BufferedReader],out: scala.tools.nsc.interpreter.JPrintWriter)scala.tools.nsc.interpreter.SparkILoop
[error]  cannot be applied to (Option[java.io.BufferedReader], tools.nsc.interpreter.JPrintWriter, Option[String])
[error]                      ) extends SparkILoop(in0, out, master) {
[error]                                ^

Yes, I do seem to need 2.11 and 1.4.0.  The reason is that the spark installation on my cluster is 1.4 and 2.11.  Trying to build against any other combination (e.g., 1.3.1 and 2.10, 1.4.0 and 2.10) and the resulting jar produces this error when used:  

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/repl/SparkILoop
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)

Any suggestions?  Help appreciated.

**Comment by elbamos** [comment]
Oh just for completion -- the same error comes up when I try to run against the jar downloadable from here as the "release."

**Comment by elbamos** [comment]
Closing out old stale issues.
