### ISSUE TITLE
Kernel restart issue

### ISSUE THREAD

**Issue by jjonez** [tribbloid/ISpark#26]
I'm running brach IPython-3.x. When I restart the kernel in Jupyterhub, I frequently get a failure. Am I doing something wrong or is this an issue? I get this message:

"The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened."

Here is the error in the log:

16/06/15 12:52:05 INFO Client: Application report for application_1465935646593_0014 (state: ACCEPTED)
16/06/15 12:52:06 INFO Client: Application report for application_1465935646593_0014 (state: ACCEPTED)
[W 2016-06-15 12:52:07.726 jim kernelmanager:130] Timeout waiting for kernel_info_reply: 1495b014-a6bd-4b2d-8923-7c2af0cff7fe
[E 2016-06-15 12:52:07.726 jim handlers:90] Exception restarting kernel
    Traceback (most recent call last):
      File "/opt/Anaconda3/lib/python3.5/site-packages/notebook/services/kernels/handlers.py", line 88, in post
        yield gen.maybe_future(km.restart_kernel(kernel_id))
      File "/opt/Anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/opt/Anaconda3/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    tornado.gen.TimeoutError: Timeout waiting for restart

**Comment by tribbloid** [comment]
Do you have version numbers? (Spark? Scala? Java? IPython)
The latest build is for 1.3.1, didn't maintain it for some time (busy busy). But I'll try to reproduce it.
Also, if you found a fork that has supported spark 1.4+ plz let me know

**Comment by jjonez** [comment]
Hi. Thanks for the reply. Here's what we are using:
Spark - 1.6.1
Hadoop 2.7.1
Scala - 2.10.4
IPython - 4.2.0

I made no changes when I built branch , including the pom Spark or Hadoop versions. It seems that if it fails and I wait long enough before doing the "try restarting now", it usually will restart. So, I'm wondering if I am restarting while it is in the process of initializing a spark context or something. This may be purely user error or misunderstanding. Thanks for the help.

**Comment by tribbloid** [comment]
oooooooh I remember not including 1.6.x in my dependency list (which means I'm using deprecated API).
This probably take some time to fix, would you mind taking a look of forked projects at the moment?
