### ISSUE TITLE
Java Issue when run ipython

### ISSUE THREAD

**Issue by titipata** [tribbloid/ISpark#5]
I installed `ISpark` and followed the documentation. However, when I run `ipython`, I got following error

```
Exception in thread "main" java.lang.NoClassDefFoundError: play/api/libs/json/Reads
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:274)
    at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:319)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: play.api.libs.json.Reads
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 5 more
```

**Comment by H4ml3t** [comment]
Hi, I'm using the ```ispark-core-0.2.0-SNAPSHOT.jar``` and I'm having the same issues, no trace of any "assembly" jar :(
```
Exception in thread "main" java.lang.NoClassDefFoundError: play/api/libs/json/Reads
```

please help!

**Comment by elbamos** [comment]
Me too, and also don't have an "assembly" jar with 0.2

**Comment by H4ml3t** [comment]
issue inside the target folder
```
find . -name "*assembly*"
```
L
